from typing import Any

def isInt(x: Any) -> bool: ...
def isFloat(x: Any) -> bool: ...
def isComplex(x: Any) -> bool: ...
def isStr(x: Any) -> bool: ...
def isList(x: Any) -> bool: ...
def isTuple(x: Any) -> bool: ...
def isDict(x: Any) -> bool: ...
def isSet(x: Any) -> bool: ...
def isCallable(x: Any) -> bool: ...
def isIterable(x: Any) -> bool: ...
def isIterator(x: Any) -> bool: ...
def isGenerator(x: Any) -> bool: ...
def isBool(x: Any) -> bool: ...
def isNone(x: Any) -> bool: ...
