from typing import Any

def isInteger(x: Any) -> bool: ...
def isString(x: Any) -> bool: ...
def isDictionary(x: Any) -> bool: ...
def isBoolean(x: Any) -> bool: ...
def isNum(x: Any) -> bool: ...
def isChar(x: Any) -> bool: ...
def isMap(x: Any) -> bool: ...
def isFunc(x: Any) -> bool: ...
