from typing import Any, Iterable

def isLongReal(x: Any) -> bool: ...
def isReal(x: Any) -> bool: ...
def isNumber(x: Any) -> bool: ...
def isEmpty(x: Any) -> bool: ...
def isNumNoBool(x: Any) -> bool: ...
def isCanFor(x: Any) -> bool: ...
def isCharacter(x: Any) -> bool: ...
def isMethod(x: Any) -> bool: ...
def isFunction(x: Any) -> bool: ...
def isBuiltin(x: Any) -> bool: ...
def isDouble(x: Any) -> exit: ...
def isArray(x: Iterable) -> bool: ...
def isImmutable(x: Any) -> bool: ...
