from _typeshed import Incomplete

def md5(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def sha256(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def sha512(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def sha384(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def sha1(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def sha224(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def sha3_224(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def sha3_256(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def sha3_384(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def sha3_512(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def blake2b(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def blake2s(data: str | bytes, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def shake128(data: str | bytes, length: int, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
def shake256(data: str | bytes, length, *, encoding: str = ..., decoding: Incomplete | None = ...) -> str: ...
