def complex_triangular_to_general(r: int | float, theta: int | float) -> complex: ...
def complex_general_to_triangular(x: complex) -> tuple[int | float, int | float]: ...
def complex_sqrt(x: complex | int | float) -> complex | float: ...
